# Generated by Django 4.0.10 on 2024-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Task description', max_length=128)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Medium', 'High')], default='Low', help_text='Task priority', max_length=9, null=True)),
                ('estimation', models.FloatField(blank=True, default=0.0, help_text='Task estimation in hours', null=True)),
            ],
        ),
    ]
