# Generated by Django 4.0.10 on 2024-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.AddField(
            model_name='car',
            name='mmileage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
